name: Build and Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Disable Run-From-Package
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name nobelyashapp \
              --resource-group yashnobelkrishna_group \
              --settings WEBSITE_RUN_FROM_PACKAGE=0

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: nobelyashapp
          slot-name: production
          package: .
          startup-command: gunicorn app:app --bind=0.0.0.0:$PORT --timeout 600

      - name: Restart Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp restart \
              --name nobelyashapp \
              --resource-group yashnobelkrishna_group
